# Generated by Django 3.2.25 on 2026-01-28 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Device display name', max_length=100)),
                ('device_id', models.CharField(help_text='Unique device identifier (serial number or MAC address)', max_length=100, unique=True)),
                ('device_type', models.CharField(choices=[('bp_monitor', 'Blood Pressure Monitor'), ('glucometer', 'Glucometer'), ('weight_scale', 'Weight Scale'), ('thermometer', 'Thermometer'), ('oximeter', 'Pulse Oximeter'), ('ecg', 'ECG Device'), ('other', 'Other')], default='other', help_text='Type of medical device', max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=50)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired')], default='inactive', help_text='Current status of the device', max_length=20)),
                ('last_calibration_date', models.DateField(blank=True, null=True)),
                ('next_calibration_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, help_text='Physical location of the device', max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, help_text='Additional notes about the device')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this device should be treated as active.')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User currently assigned to this device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'device',
                'verbose_name_plural': 'devices',
                'ordering': ['device_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_type', models.CharField(help_text='Type of reading (e.g., blood_pressure, blood_glucose)', max_length=50)),
                ('reading_data', models.JSONField(help_text='Structured data for the reading (format depends on device type)')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the reading was taken')),
                ('notes', models.TextField(blank=True)),
                ('device', models.ForeignKey(help_text='Device that generated this reading', on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.device')),
                ('patient', models.ForeignKey(help_text='Patient this reading belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='device_readings', to='patients.patient')),
                ('recorded_by', models.ForeignKey(help_text='User who recorded this reading', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'device reading',
                'verbose_name_plural': 'device readings',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
