# Generated by Django 3.2.25 on 2026-01-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='connection_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('connected', 'Connected'), ('disconnected', 'Disconnected')], default='unknown', help_text='Connectivity status (from heartbeat/agent)', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='is_busy',
            field=models.BooleanField(default=False, help_text='Whether the device is currently busy (in an active session)'),
        ),
        migrations.AddField(
            model_name='device',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Whether the device is locked for an active screening session'),
        ),
        migrations.AddField(
            model_name='device',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, help_text='Last heartbeat timestamp received from device/gateway', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='locked_session_id',
            field=models.CharField(blank=True, help_text='Screening session identifier that holds the lock (if any)', max_length=100),
        ),
    ]
