# Generated by Django 3.2.25 on 2026-01-28 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('questionnaires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_doctor_review', models.BooleanField(default=False)),
                ('recommended_frequency', models.PositiveIntegerField(default=0, help_text='Recommended days between screenings (0 for one-time screenings)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_screening_questionnaire', models.ForeignKey(blank=True, help_text='Questionnaire to be completed after screening', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_screening_types', to='questionnaires.questionnaire')),
                ('pre_screening_questionnaire', models.ForeignKey(blank=True, help_text='Questionnaire to be completed before screening', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_screening_types', to='questionnaires.questionnaire')),
            ],
            options={
                'verbose_name': 'screening type',
                'verbose_name_plural': 'screening types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('result_status', models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('inconclusive', 'Inconclusive'), ('pending', 'Pending Review')], default='pending', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conducted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_screenings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_screenings', to=settings.AUTH_USER_MODEL)),
                ('device_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_sessions', to='devices.device')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_sessions', to='patients.patient')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_screenings', to=settings.AUTH_USER_MODEL)),
                ('screening_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='screening.screeningtype')),
            ],
            options={
                'verbose_name': 'screening session',
                'verbose_name_plural': 'screening sessions',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_data', models.JSONField()),
                ('findings', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('needs_follow_up', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening_result', to='screening.screeningsession')),
            ],
            options={
                'verbose_name': 'screening result',
                'verbose_name_plural': 'screening results',
            },
        ),
        migrations.CreateModel(
            name='ScreeningReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('upcoming', 'Upcoming Screening'), ('overdue', 'Overdue Screening'), ('follow_up', 'Follow-up Required')], max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_via', models.CharField(blank=True, max_length=50)),
                ('is_sent', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='screening.screeningsession')),
            ],
            options={
                'verbose_name': 'screening reminder',
                'verbose_name_plural': 'screening reminders',
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='screening_attachments/%Y/%m/%d/')),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='screening.screeningsession')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'screening attachment',
                'verbose_name_plural': 'screening attachments',
                'ordering': ['-created_at'],
            },
        ),
    ]
