# Generated by Django 3.2.25 on 2026-01-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningsession',
            name='consent_obtained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screeningsession',
            name='consent_text_version',
            field=models.TextField(blank=True, help_text='Consent text/version shown to the patient (store immutably per session)'),
        ),
        migrations.AddField(
            model_name='screeningsession',
            name='consented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screeningtype',
            name='supported_device_types',
            field=models.JSONField(blank=True, default=list, help_text='List of supported device_type values for this screening type'),
        ),
    ]
