# Generated by Django 3.2.25 on 2026-03-20 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_repad_patient_ids'),
        ('screening', '0004_screeningsession_vitals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningsession',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='screeningsession',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening_session', to='patients.patient'),
        ),
    ]
