# Generated by Django 3.2.25 on 2026-01-28 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('number_answer', models.FloatField(blank=True, null=True)),
                ('date_answer', models.DateField(blank=True, null=True)),
                ('file_answer', models.FileField(blank=True, null=True, upload_to='questionnaire_answers/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
                'ordering': ['question__display_order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('help_text', models.TextField(blank=True)),
                ('question_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('radio', 'Multiple Choice (Single Answer)'), ('checkbox', 'Multiple Choice (Multiple Answers)'), ('select', 'Dropdown'), ('rating', 'Rating Scale'), ('date', 'Date'), ('email', 'Email'), ('number', 'Number'), ('file', 'File Upload')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depends_on_value', models.TextField(blank=True, null=True)),
                ('allowed_file_types', models.CharField(blank=True, max_length=200)),
                ('max_file_size', models.PositiveIntegerField(default=5, help_text='Maximum file size in MB')),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('min_label', models.CharField(blank=True, max_length=50)),
                ('max_label', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('questionnaire_type', models.CharField(choices=[('screening', 'Screening'), ('assessment', 'Assessment'), ('follow_up', 'Follow-up'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'questionnaire',
                'verbose_name_plural': 'questionnaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'question option',
                'verbose_name_plural': 'question options',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_responses', to='patients.patient')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='questionnaires.questionnaire')),
                ('respondent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaire_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'response',
                'verbose_name_plural': 'responses',
                'ordering': ['-submitted_at', '-started_at'],
            },
        ),
    ]
