# Generated by Django 3.2.25 on 2026-01-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='is_image_primary',
            field=models.BooleanField(default=False, help_text='Display image instead of text'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='option_image',
            field=models.ImageField(blank=True, help_text='Optional image for this option', null=True, upload_to='question_options/'),
        ),
    ]
