# Generated by Django 3.2.25 on 2026-02-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_auto_20260130_0543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['question__order'], 'verbose_name': 'answer', 'verbose_name_plural': 'answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='questionoption',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='display_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question_text',
        ),
        migrations.RenameField(
            model_name='questionoption',
            old_name='display_order',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='question',
            name='allowed_file_types',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='depends_on_question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='depends_on_value',
        ),
        migrations.RemoveField(
            model_name='question',
            name='help_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='max_file_size',
        ),
        migrations.RemoveField(
            model_name='question',
            name='max_label',
        ),
        migrations.RemoveField(
            model_name='question',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='question',
            name='min_label',
        ),
        migrations.RemoveField(
            model_name='question',
            name='min_value',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='is_image_primary',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='value',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('yes_no', 'Yes/No'), ('true_false', 'True/False'), ('multiple_choice', 'Multiple Choice'), ('short_answer', 'Short Answer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='option_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_options/'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
