# Generated by Django 3.2.25 on 2026-02-20 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0005_add_attachment_question_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='question',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='questionnaires.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='trigger_answer',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('parent', 'trigger_answer')},
        ),
    ]
