# Generated by Django 3.2.25 on 2026-03-06 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0006_auto_20260221_0355'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
    ]
