# Generated by Django 3.2.25 on 2026-03-19 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_repad_patient_ids'),
        ('questionnaires', '0009_question_allow_multiple_selections'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='vitals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaire_responses', to='patients.patientvitals'),
        ),
    ]
