# Generated by Django 3.2.25 on 2026-01-28 16:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Prefer not to say')], default='U', max_length=1, verbose_name='gender')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='phone number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='state/province')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, verbose_name='emergency contact name')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='emergency contact phone')),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=100, verbose_name='relation to patient')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic_bp', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='systolic BP (mmHg)')),
                ('diastolic_bp', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='diastolic BP (mmHg)')),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='heart rate (bpm)')),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='respiratory rate (bpm)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='temperature (°C)')),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='oxygen saturation (%)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='weight (kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='height (cm)')),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='BMI')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='recorded at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_vital_signs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vital signs',
                'verbose_name_plural': 'vital signs',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('GENERAL', 'General Note'), ('CONSULTATION', 'Consultation'), ('FOLLOW_UP', 'Follow-up'), ('TREATMENT', 'Treatment'), ('OTHER', 'Other')], default='GENERAL', max_length=20, verbose_name='note type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_important', models.BooleanField(default=False, verbose_name='important')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_notes', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='patients.patient')),
            ],
            options={
                'verbose_name': 'patient note',
                'verbose_name_plural': 'patient notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(blank=True, max_length=10, verbose_name='blood type')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='height (cm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='weight (kg)')),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='BMI')),
                ('allergies', models.TextField(blank=True, verbose_name='allergies')),
                ('current_medications', models.TextField(blank=True, verbose_name='current medications')),
                ('past_medications', models.TextField(blank=True, verbose_name='past medications')),
                ('chronic_conditions', models.TextField(blank=True, verbose_name='chronic conditions')),
                ('surgeries', models.TextField(blank=True, verbose_name='surgeries')),
                ('family_history', models.TextField(blank=True, verbose_name='family medical history')),
                ('notes', models.TextField(blank=True, verbose_name='additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='patients.patient')),
            ],
            options={
                'verbose_name': 'medical record',
                'verbose_name_plural': 'medical records',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PRESCRIPTION', 'Prescription'), ('REPORT', 'Medical Report'), ('SCAN', 'Scan/Image'), ('LAB_RESULT', 'Lab Result'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='document type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('file', models.FileField(upload_to='patient_documents/%Y/%m/%d/', verbose_name='file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
