# Generated by Django 3.2.25 on 2026-02-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_patient_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['patient_id'], 'verbose_name': 'patient', 'verbose_name_plural': 'patients'},
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='patient ID'),
        ),
    ]
