# Generated by Django 3.2.25 on 2026-02-03 16:37

from django.db import migrations


def generate_patient_id(apps, schema_editor):
    """Generate patient IDs for existing patients"""
    Patient = apps.get_model('patients', 'Patient')
    
    # Get all patients without patient_id
    patients = Patient.objects.filter(patient_id__isnull=True).order_by('id')
    
    for i, patient in enumerate(patients, 1):
        # Generate patient ID in format MDCP0001, MDCP0002, etc.
        patient.patient_id = f"MDCP{i:04d}"
        patient.save()


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20260203_2207'),
    ]

    operations = [
        migrations.RunPython(generate_patient_id),
    ]
