# Generated by Django 3.2.25 on 2026-02-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20260203_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='phone number'),
        ),
    ]
