# Generated by Django 3.2.25 on 2026-02-21 22:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0006_alter_patient_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='weight (kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='height (cm)')),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, null=True, verbose_name='systolic BP (mmHg)')),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, null=True, verbose_name='diastolic BP (mmHg)')),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='heart rate (bpm)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='temperature (°C)')),
                ('spo2', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='SpO2 (%)')),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='respiratory rate (breaths/min)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='recorded at')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.patient', verbose_name='patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_vitals', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
            ],
            options={
                'verbose_name': 'patient vitals',
                'verbose_name_plural': 'patient vitals',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
