# Generated by Django 3.2.25 on 2026-04-10 09:56

from django.db import migrations

def create_missing_sessions(apps, schema_editor):
    Patient = apps.get_model('patients', 'Patient')
    ScreeningSession = apps.get_model('screening', 'ScreeningSession')
    ScreeningType = apps.get_model('screening', 'ScreeningType')

    # Get the default General Health screening type (as fallback)
    default_type = ScreeningType.objects.filter(is_active=True).first()

    if not default_type:
        default_type, _ = ScreeningType.objects.get_or_create(
            name="General Health Screening",
            defaults={"description": "Standard general health screening", "is_active": True}
        )
    
    from django.utils import timezone
    User = apps.get_model('accounts', 'User')

    # Loop over all patients to find those with no ScreeningSession
    for patient in Patient.objects.all():
        if not ScreeningSession.objects.filter(patient=patient).exists():
            # Auto-create the missing session!
            session = ScreeningSession.objects.create(
                id=patient.patient_id,
                patient=patient,
                screening_type=default_type,
                status='scheduled', # Safe fallback status
                scheduled_date=timezone.now(),
            )
            
            # 1. Sync created_by
            if patient.created_by:
                session.created_by = patient.created_by
            else:
                # Fallback: assign to the first available Health Assistant if possible
                ha = User.objects.filter(role='HEALTH_ASSISTANT').first()
                session.created_by = ha
                
            session.save()
            
            # 2. Sync created_at historically to match the patient precisely
            ScreeningSession.objects.filter(id=session.id).update(created_at=patient.created_at)

def reverse_create_missing_sessions(apps, schema_editor):
    pass # Reverse logic is safely ignored since we don't track which ones were retro-created

class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_repad_patient_ids'),
        ('screening', '0005_auto_20260320_1655'),
    ]

    operations = [
        migrations.RunPython(create_missing_sessions, reverse_create_missing_sessions),
    ]
